name: application
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dependency:
    path: ../dependency/
  meta: ^1.3.0
  reflectable: ^3.0.2

dev_dependencies:
  build_runner: ^2.0.0
  lint: ^1.5.0
  test: ^1.16.5

dependency_overrides:
  conduit_isolate_exec:
    path: ../../isolate_exec
